
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Apr 24 2025 02:18:51 IST (Apr 23 2025 20:48:51 UTC)

// Verification Directory fv/PropFA 

module PropFA(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1;
  OAI32X1 g95__2398(.A0 (cin), .A1 (a), .A2 (n_1), .B0 (b), .B1 (n_0),
       .Y (sum));
  NOR2XL g96__5107(.A (n_1), .B (n_0), .Y (cout));
  XNOR2X1 g97__6260(.A (cin), .B (a), .Y (n_0));
  INVXL g98(.A (b), .Y (n_1));
endmodule

