
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Apr 24 2025 02:26:55 IST (Apr 23 2025 20:56:55 UTC)

// Verification Directory fv/full_adder_o 

module full_adder_o(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g171__2398(.A (a), .B (b), .CI (cin), .CO (carry), .S (sum));
endmodule

